app/Checklist.php
<?php

namespace App;

use App\Models\Traits\HasOwner;
use Illuminate\Database\Eloquent\Model;

class Checklist extends Model
{
    use HasOwner;
    /*
     * Checklist type
     * 0 - blueprint
     * 1 - regular checklist
     * 2 - running
     * 3 - completed
     * */
    protected $guarded = [];

    public function points()
    {
        return $this->hasMany('App\Point');
    }

    public function getBlueprintAttribute()
    {
        if ($this->type == 0) {
            return true;
        }
        return false;
    }


    public function getStatusAttribute()
    {
        switch ($this->type) {
            case 0:
                return 'blueprint';
            case 1:
                return 'regular';
            case 2:
                return 'running';
            case 3:
                return 'complete';
            default:
                return 'unknown beast';
        }
    }

    public function getOrderedPointsAttribute()
    {
        return $this->points->sortBy('order');
    }
}

app/Point.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Point extends Model
{
    //

    protected $guarded = [];

    public function checklist()
    {
        return $this->belongsTo('App\Checklist', 'checklist_id');
    }

    /*
     * Point statu
     * */
    public function getPointStatusAttribute()
    {
        return $this->status;
    }

    public function getIsCompleteAttribute()
    {
        if ($this->status == 'complete') {
            return true;
        };
        return false;
    }
}

app/Http/Controllers/ChecklistController.php
<?php

namespace App\Http\Controllers;

use App\Checklist;
use App\Point;
use App\Repositories\Checklist\DbChecklistRepository;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class ChecklistController extends Controller
{
    /**
     * @var DbChecklistRepository
     */
    private $repository;

    /**
     * ChecklistController constructor.
     * @param DbChecklistRepository $repository
     */
    public function __construct(DbChecklistRepository $repository)
    {
        $this->repository = $repository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //TODO get own instead
        $checklists = $this->repository->getOwned();

        return view('checklists.checklists.index', compact('checklists'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('checklists.checklists.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $this->repository->createFromFormRequest($request);
        return redirect()->route('checklist.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $checklist = $this->repository->getById($id);
        return view('checklists.checklists.show', compact('checklist'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $checklist = $this->repository->getById($id);
        return view('checklists.checklists.edit', compact('checklist'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->repository->updateFromFormRequest($id, $request);
        return redirect()->route('checklist.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $this->repository->delete($id);
        return redirect()->back();
    }


    public function addPoint($id)
    {
        $checklist = $this->repository->getById($id);
        return view('checklists.points.create_for_checklist', compact('checklist'));
    }

    public function getBlueprints()
    {
        $allChecklists = $this->repository->getOwned();
        $checklists = $allChecklists->filter(function ($checklist) {
            if ($checklist->blueprint) {
                return true;
            }
            return false;
        });
        return view('checklists.checklists.index', compact('checklists'));
    }

    public function startBlueprint($id)
    {
        $blueprint = $this->repository->getById($id);
        $blueprintPoints = $blueprint->points;
        $checklist = factory(Checklist::class)->create([
            'name'        => $blueprint->name,
            'description' => $blueprint->description,
            'user_id'     => $blueprint->user_id,
            'type'        => 2
        ]);
        foreach ($blueprintPoints as $point) {
            $checlistPoints[] = factory(Point::class)->create([
                'name'         => $point->name,
                'description'  => $point->description,
                'checklist_id' => $checklist->id,
                'status'       => 'active'
            ]);
        }
        return redirect()->route('checklist.show', $checklist->id);
    }

    public function reorder($id)
    {
        $lastItem = $this->repository->getLastItemOrder($id);
        return redirect()->back();
    }

    public function running()
    {
        $checklists = $this->repository->getOwnRunning();
        return view('checklists.checklists.pages.running', compact('checklists'));
    }
}

app/Http/Controllers/PointController.php
<?php

namespace App\Http\Controllers;

use App\Checklist;
use App\Point;
use App\Repositories\Checklist\DbChecklistRepository;
use App\Repositories\Checklist\DbPointRepository;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class PointController extends Controller
{
    /**
     * @var DbPointRepository
     */
    private $repository;
    /**
     * @var DbChecklistRepository
     */
    private $checklistRepository;

    /**
     * PointController constructor.
     * @param DbPointRepository $repository
     * @param DbChecklistRepository $checklistRepository
     */
    public function __construct(DbPointRepository $repository, DbChecklistRepository $checklistRepository)
    {
        $this->repository = $repository;
        $this->checklistRepository = $checklistRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $points = $this->repository->getOwned();
        return view('checklists.points.index', compact('points'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $checklists = $this->checklistRepository->getOwned();
        return view('checklists.points.create', compact('checklists'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $point = $this->repository->createFromFormRequest($request);
        $checklist = $point->checklist;
        return redirect()->route('checklist.show', [$checklist->id] );
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $point = $this->repository->getById($id);
        return view('checklists.points.show', compact('point'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $point = $this->repository->getById($id);
        $checklists = $this->checklistRepository->getOwned();
        return view('checklists.points.edit', compact('point', 'checklists'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $data = $request->except('_method', '_token');
        $point = Point::find($id);
        $point->update($data);
        return redirect()->route('point.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        Point::destroy($id);
        return redirect()->route('point.index');
    }

    public function moveUp($id)
    {
        $this->repository->moveUp($id);
        $checklist = $this->repository->findById($id)->checklist;
        return redirect()->back();
    }
    public function moveDown($id)
    {
        $this->repository->moveDown($id);
        $checklist = $this->repository->findById($id)->checklist;
        return redirect()->back();
    }

    public function setStatus($id, $status)
    {
        $point = $this->repository->getById($id);
        $point->status = $status;
        $checklist = $point->checklist;
        $point->save();
        return redirect()->back();
    }
}

resources/views/checklists/points/_point_list_item.blade.php
@component('parts.components.panel._panel')
    @slot('title')
        {{$point->name}}
    @endslot
    @slot('subtitle')
        order: {{$point->order}}
        status: {{ $point->point_status }}

    @endslot

    @component('parts.components.collapse._collapsable')

        <p>
            {{$point->description}}
        </p>
        <p>Status: {{$point->status}}</p>
        <p>Checklist: {{$point->checklist->name}}</p>

    @endcomponent

    @component('parts.components.buttons.dropdown_button')
        <li><a href="{!! route('point.show', [$point->id]) !!}" id="showPoint{{$point->id}}">
            <button type="button"  class="btn btn-success">Show</button>
        </a></li>
        <li><a href="{!! route('point.edit', [$point->id]) !!}" id="editPoint{{$point->id}}">
            <button type="button"  class="btn btn-warning">Edit</button>
        </a></li>
        <li><a href="{!! route('point.delete', [$point->id]) !!}" id="deletePoint{{$point->id}}">
            <button type="button"  class="btn btn-danger">Del</button>
        </a></li>
        <li><a href="{!! route('point.status', [$point->id, 'complete']) !!}" id="completePoint{{$point->id}}">
            <button type="button"  class="btn btn-success">complete</button>
        </a></li>
        <li><a href="{!! route('point.status', [$point->id, 'active']) !!}" id="activePoint{{$point->id}}">
        <button type="button"  class="btn btn-warning">active</button>
    </a></li>
        <li>
            <a href="{!! route('point.moveup', [$point->id]) !!}">UP</a>
        </li>
        <li>
            <a href="{!! route('point.movedown', [$point->id]) !!}">DOWN</a>
        </li>

    @endcomponent

@endcomponent

resources/views/checklists/points/create.blade.php
@extends('layouts.master')

@section('title')
    Point create
@stop

@section('content')
    <div class="panel panel-success">
        <div class="panel-heading">
            <h3 class="panel-title">Create point</h3>
        </div>
        <div class="panel-body">
            <form action="{!! route('point.store') !!}" method="post" role="form">
                {{csrf_field()}}
                <div class="form-group">
                    <label for="name">name</label>
                    <input type="text" class="form-control" name="name" id="name">
                </div>

                <div class="form-group">
                    <label for="description">description</label>
                    <input type="text" class="form-control" name="description" id="description">
                </div>

                <select name="checklist_id" id="checklist" class="form-control">
                    @foreach($checklists as $checklist)
                        <option value="{{$checklist->id}}">{{$checklist->name}}</option>
                    @endforeach
                </select>

                <select name="status" id="status" class="form-control">
                	<option value="active">active</option>
                	<option value="done">done</option>
                </select>

                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
@stop

resources/views/checklists/points/create_for_checklist.blade.php
@extends('layouts.master')

@section('title')
    Point create
@stop

@section('content')
    <div class="panel panel-success">
        <div class="panel-heading">
            <h3 class="panel-title">Create point</h3>
        </div>
        <div class="panel-body">
            <form action="{!! route('point.store') !!}" method="post" role="form">
                {{csrf_field()}}
                <div class="form-group">
                    <label for="name">name</label>
                    <input type="text" class="form-control" name="name" id="name">
                </div>

                <div class="form-group">
                    <label for="description">description</label>
                    <input type="text" class="form-control" name="description" id="description">
                </div>

               <div class="form-group">
                   <input type="text" name="checklist_id" class="hidden" value="{{$checklist->id}}">
               </div>

                <select name="status" id="status" class="form-control">
                	<option value="active">active</option>
                	<option value="done">done</option>
                </select>

                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
@stop

resources/views/checklists/points/edit.blade.php
@extends('layouts.master')

@section('title')
    Point edit
@stop

@section('content')
    <div class="panel panel-warning">
    	  <div class="panel-heading">
    			<h3 class="panel-title">Edit point</h3>
    	  </div>
    	  <div class="panel-body">

			  <form action="{!! route('point.update', [$point->id]) !!}"  method="post" role="form">
				  {{csrf_field()}}
				  <input name="_method" type="hidden" value="PUT">

				  <div class="form-group">
					  <label for="name">name</label>
					  <input type="text" class="form-control" name="name" id="name" value="{{$point->name}}">
				  </div>

				  <div class="form-group">
					  <label for="description">description</label>
					  <input type="text" class="form-control" name="description" id="description" value="{{$point->description}}">
				  </div>

				  <select name="checklist_id" id="checklist" class="form-control">
					  @foreach($checklists as $checklist)
						  <option value="{{$checklist->id}}">{{$checklist->name}}</option>
					  @endforeach
				  </select>

				  <button type="submit" class="btn btn-primary">Submit</button>
			  </form>
    	  </div>
    </div>
@stop

resources/views/checklists/points/index.blade.php
@extends('layouts.master')

@section('title')
    Point list
@stop

@section('content')
    <a href="{!! route('point.create') !!}" id="createPoint">
        <button type="button"  class="btn btn-success pull-right">Create point</button>
    </a>
        @foreach($points as $point)
           @include('checklists.points._point_list_item')
        @endforeach
@stop

resources/views/checklists/points/show.blade.php
@extends('layouts.master')

@section('title')
    Point show
@stop

@section('content')
    <div class="panel panel-success">
    	  <div class="panel-heading">
    			<h3 class="panel-title">{{$point->name}}</h3>
    	  </div>
    	  <div class="panel-body">
    			<p>{{$point->description}}</p>
    	  </div>
    </div>
@stop